:_module-type: PROCEDURE

[id="managing-role-based-access-control-from-openshift_{context}"]
= Managing role-based access control from {openshift-platform}

[role='_abstract']
As a cluster admin, you can manage access to a model registry from {openshift-platform}. You can grant access to individual users and user groups in your organization, and for service accounts in a project.

ifdef::upstream[]
The model registry operator uses {openshift-platform} Role-Based Access Control (RBAC), and creates various RBAC resources in the `odh-model-registries` namespace.
endif::[]

ifndef::upstream[]
The model registry operator uses {openshift-platform} Role-Based Access Control (RBAC), and creates various RBAC resources in the `rhoai-model-registries` namespace.
endif::[]

For each model registry instance, the operator creates a `registry-users-<model registry instance name>` role which has the following access rules:
+
[source]
----
 rules:
- apiGroups:
  - ""
  resourceNames:
  - {{Name}}
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - {{Name}}
  resources:
  - endpoints
  verbs:
  - get
----

You can grant an individual user or service account access to the model registry service by creating a role binding to the `registry-users-<model registry instance name>` role.

The model registry operator also creates an {openshift-platform} group called `<model registry instance name>-users`, which has a role binding to the `registry-users-<model registry instance name>` role. You can add users to this group to grant them access to the model registry instance without needing to create a role binding for each user.

To enable access for all cluster users, add `system:authenticated` to the group list.


.Prerequisites
* You have logged in to {openshift-platform} with the `cluster-admin` role.
* An available model registry exists in your {productname-short} deployment.
ifdef::upstream[]
* The users and groups that you want to provide access to already exist in {openshift-platform}. For more information, see
link:{odhdocshome}/managing-odh/#managing-users-and-groups[Managing users and groups].
endif::[]

ifndef::upstream[]
* The users and groups that you want to provide access to already exist in {openshift-platform}. For more information, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-users-and-groups[Managing users and groups].
endif::[]

.Procedure
. In the {openshift-platform} console, click
.

.Verification
* Users, groups, and accounts that were granted access to a model registry can register, view, edit, version, deploy, delete, archive, and restore models in that registry.





